# Generated by Django 3.2.5 on 2021-08-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210812_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_stackoverflow',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
