# Generated by Django 3.2.5 on 2021-08-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210812_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
