# Generated by Django 3.2.5 on 2021-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_roles',
            field=models.CharField(choices=[('Student', 'Student'), ('Developer', 'Developer'), ('Teacher', 'Teacher'), ('Admin', 'Admin')], default='Student', help_text='By Default is Student. Developer, Teacher, Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('up', 'up vote'), ('down', 'down vote')], max_length=50),
        ),
    ]
