# Generated by Django 3.2.5 on 2021-07-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20210727_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='role',
            new_name='organization_role',
        ),
    ]
