# Generated by Django 3.2.5 on 2021-07-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_role_myuser_organization_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='job_title',
            field=models.CharField(default='Student', help_text='By Default is Student. Admin, Developer, Teacher, Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='organization_role',
            field=models.CharField(default='Developer', help_text='Like Node.js, Python, ROR or Django developer', max_length=100),
        ),
    ]
