# Generated by Django 3.2.5 on 2021-07-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210728_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.BigIntegerField(blank=True, max_length=11, null=True),
        ),
    ]
