# Generated by Django 3.2.5 on 2021-07-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
