# Generated by Django 3.2.5 on 2021-07-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210728_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='job_title',
            field=models.CharField(default='Programmer', help_text='Like Node.js, Python, ROR or Django developer', max_length=100),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='organization_role',
            field=models.CharField(choices=[('Student', 'Student'), ('Developer', 'Developer'), ('Teacher', 'Teacher')], default='Student', help_text='By Default is Student. Developer, Teacher, Student', max_length=100),
        ),
    ]
